name: Mail
description: Mail Plugin
author: StarTux
version: 0.1
website: https://cavetale.com
main: com.winthier.mail.MailPlugin
depend: [ SQL ]
commands:
  mailto:
    description: Send mail
    permission: mail.mailto
    usage: /mailto <player> <message:
  mail:
    description: Mailbox access
    permission: mail.mail
    usage: |-
      /mailto - See unread mail
      /mailto all - See all mail
permissions:
  mail.mail:
    description: Read mail
  mail.mailto:
    description: Send mail
