name: Mail
version: 0.1
description: Mail Plugin
author: StarTux
api-version: 1.13
website: https://github.com/StarTux/Mail
main: com.winthier.mail.MailPlugin
depend: [SQL]
softdepend: []
commands:
  mailto:
    description: Send mail
    permission: mail.mailto
    usage: /mailto <player> <message>
  mail:
    description: Mailbox access
    permission: mail.mail
    usage: |-
      /mail - See unread mail
      /mail all - See all mail
permissions:
  mail.mail:
    description: Read mail
  mail.mailto:
    description: Send mail
