main: com.winthier.mail.MailPlugin
name: Mail

version: 0.1
api-version: 1.19

description: Mail Plugin
author: StarTux
website: https://github.com/StarTux/Mail

depend: [Core, SQL, Chat]
softdepend: []

commands:

  mailto:
    description: Send mail
    permission: mail.mailto
    usage: /mailto <player> <message>

  mail:
    description: Mailbox access
    permission: mail.mail
    usage: |-
      /mail - See unread mail
      /mail all - See all mail

permissions:
  mail.mail:
    description: Read mail
    default: op

  mail.mailto:
    description: Send mail
    default: op

  mail.emoji:
    description: Use emoji in mails
    default: op
