name: Mail
description: Mail Plugin
author: StarTux
version: 0.1
main: com.winthier.mail.MailPlugin
depend: [ SQL ]
commands:
  mailto:
    description: Send mail
    permission: mail.mailto
  mail:
    description: Mailbox access
    permission: mail.mail
permissions:
  mail.mail:
    description: Read mail
  mail.mailto:
    description: Send mail
